package com.mj.springboot;


import org.junit.jupiter.api.Test;

class SpringbootApplicationTests {

    @Test
    void contextLoads() throws Exception {
        String str = "/NWP_NMC_T639G/H00H72/PUB\n" +
                "/NWP_NMC_T639G/H72H96/PUB\n" +
                "/NWP_NMC_T639G/H96H120/PUB\n" +
                "/NWP_NMC_T639G/H120/PUB\n" +
                "/NWP_NMC_T639R/H00H72/PUB\n" +
                "/NWP_NMC_T639R/H72H96/PUB\n" +
                "/NWP_NMC_T639R/H96H120/PUB\n" +
                "/NWP_NMC_T639R/H120/PUB\n" +
                "/NWP_NMC_GRAPES/H00H48/PUB\n" +
                "/NWP_NMC_GRAPES/H54/PUB\n" +
                "/NWP_NMC_GRAPES/H60/PUB\n" +
                "/SEVP_OC_001/OCEN/PUB\n" +
                "/SEVP_EN_001/ATME/PUB\n" +
                "/SEVP_EN_001/ATME/PUB\n" +
                "/NWP_MCTR_001/CLDAS/PUB\n" +
                "/NWP_MCTR_001/NCC_CLFC/PUB\n" +
                "/NWP_MCTR_001/ECMF_GLB/PUB\n" +
                "/NWP_MCTR_001/KWBC_GLB/PUB\n" +
                "/NWP_MCTR_002/ECMF_DAM/PUB\n" +
                "/NWP_MCTR_001/RJTD_GLB/PUB\n" +
                "/NWP_MCTR_001/EDZW_GLB/PUB\n" +
                "/NWP_NMC_T639GLB/PUB/PUB\n" +
                "/NWP_NMC_REPS/PUB/PUB\n" +
                "/NWP_NMC_REPS/SATE/FY2G\n" +
                "/NWP_MCTR_001/RJTD_GLB/PUB\n" +
                "/NWP_MCTR_003/JMA_GSM/PUB\n" +
                "/NWP_MCTR_003/JMA_GSM/PUB\n" +
                "/NWP_NMC_GRAPES-GFS/PUB/PUB\n" +
                "/NWP_MCTR_001/CLDAS/PUB\n" +
                "/NWP_MCTR_001/CMPA/RT\n" +
                "/NWP_MCTR_001/CMPA/NRT\n" +
                "/NWP_MCTR_001/ECMF_GLB/PUB\n" +
                "/NWP_NMC_TYPH/PUB/PUB\n" +
                "/OBS_DOM_PUB/SAND/PUB\n" +
                "/OBS_DOM_PUB/SAND/PUB\n" +
                "/OBS_DOM_PUB/SAND/PUB\n" +
                "/OBS_DOM_PUB/SAND/PUB\n" +
                "/OBS_DOM_PUB/SAND/PUB\n" +
                "/OBS_DOM_PUB/SAND/PUB\n" +
                "/OBS_DOM_PUB/SAND/PUB\n" +
                "/OBS_DOM_PUB/SAND/PUB\n" +
                "/OBS_DOM_PUB/SAND/PUB\n" +
                "/OBS_DOM_PUB/SAND/PUB\n" +
                "/OBS_DOM_PUB/SAND/PUB\n" +
                "/OBS_DOM_PUB/SAND/PUB\n" +
                "/OBS_DOM_PUB/SAND/PUB\n" +
                "/OBS_DOM_PUB/CAWN/PUB\n" +
                "/OBS_DOM_PUB/CAWN/PUB\n" +
                "/OBS_DOM_PUB/CAWN/PUB\n" +
                "/OBS_DOM_PUB/CAWN/PUB\n" +
                "/OBS_DOM_PUB/CAWN/PUB\n" +
                "/OBS_DOM_PUB/CAWN/PUB\n" +
                "/OBS_DOM_PUB/CAWN/PUB\n" +
                "/OBS_DOM_PUB/CAWN/PUB\n" +
                "/OBS_DOM_PUB/CAWN/PUB\n" +
                "/OBS_DOM_PUB/CAWN/PUB\n" +
                "/OBS_DOM_PUB/CAWN/PUB\n" +
                "/OBS_DOM_PUB/CAWN/PUB\n" +
                "/OBS_DOM_PUB/CAWN/PUB\n" +
                "/OBS_DOM_PUB/CAWN/PUB\n" +
                "/OBS_DOM_PUB/CAWN/PUB\n" +
                "/OBS_DOM_PUB/CAWN/PUB\n" +
                "/OBS_DOM_PUB/CAWN/PUB\n" +
                "/OBS_DOM_PUB/CAWN/PUB\n" +
                "/OBS_DOM_PUB/CAWN/PUB\n" +
                "/OBS_DOM_PUB/CAWN/PUB\n" +
                "/WARNING_001/PUB/WS\n" +
                "/WARNING_001/PUB/WS\n" +
                "/WARNING_001/PUB/WS\n" +
                "/WARNING_001/PUB/WS\n" +
                "/WARNING_001/PUB/WS\n" +
                "/WARNING_001/PUB/WS\n" +
                "/WARNING_001/PUB/WS\n" +
                "/WARNING_001/PUB/WS\n" +
                "/WARNING_001/PUB/WS\n" +
                "/WARNING_001/PUB/WS\n" +
                "/WARNING_001/PUB/WS\n" +
                "/WARNING_001/PUB/PROD\n" +
                "/WARNING_001/PUB/PROD\n" +
                "/RADA_PUB/NOR/IMG\n" +
                "/RADA_PUB/NOR/IMG\n" +
                "/RADA_BEPK/DOR\n" +
                "/RADA_BEPK/DOR\n" +
                "/RADA_BEPK/DOR\n" +
                "/RADA_BEPK/DOR\n" +
                "/RADA_BEPK/DOR\n" +
                "/RADA_BEPK/DOR\n" +
                "/RADA_BEPK/DOR\n" +
                "/RADA_BEPK/DOR\n" +
                "/RADA_BEPK/DOR\n" +
                "/RADA_BEPK/DOR\n" +
                "/RADA_BEPK/DOR\n" +
                "/RADA_BEPK/DOR\n" +
                "/RADA_BEPK/DOR\n" +
                "/RADA_BEPK/DOR\n" +
                "/RADA_BEPK/DOR\n" +
                "/RADA_BEPK/DOR\n" +
                "/RADA_BEPK/DOR\n" +
                "/RADA_BEPK/DOR\n" +
                "/OBS_DOM_PUB/WRPD/PUB\n" +
                "/OBS_DOM_PUB/WRPD/PUB\n" +
                "/OBS_DOM_PUB/WRPD/PUB\n" +
                "/OBS_DOM_PUB/WRPD/PUB\n" +
                "/OBS_DOM_PUB/WRPD/PUB\n" +
                "/OBS_DOM_PUB/WRPD/PUB\n" +
                "/RADA_PUB/VHHH/PUB\n" +
                "/RADA_PUB/WID/MICAPS\n" +
                "/SATE_FY2D_NOM\n" +
                "/SATE_FY2D_NOM\n" +
                "/SATE_FY2E_NOM\n" +
                "/SATE_FY2E_NOM\n" +
                "/SATE_FY2E_L2L3/SEC/R01\n" +
                "/SATE_FY2E_L2L3/DST/PUB\n" +
                "/SATE_FY2E_L2L3/PRE/PUB\n" +
                "/SATE_FY2E_L2L3/AMV/PUB\n" +
                "/SATE_FY2G_L2L3/pub/pub\n" +
                "/SATE_FY2F_NOM\n" +
                "/SATE_FY2F_NOM\n" +
                "/SATE_FY2F_L2L3\n" +
                "/SATE_FY2F_L2L3/TBB/PUB\n" +
                "/SATE_FY2F_L2L3/PRE/PUB\n" +
                "/SATE_FY2F_L2L3/SEC/PUB\n" +
                "/SATE_FY3A_L1/PUB/PUB\n" +
                "/SATE_FY3A_L1/PUB/PUB\n" +
                "/SATE_FY3A_L1/PUB/PUB\n" +
                "/SATE_FY3A_L1/PUB/PUB\n" +
                "/SATE_FY3A_L1/PUB/PUB\n" +
                "/SATE_FY3A_L1/PUB/PUB\n" +
                "/SATE_FY3A_L2L3/VIRR/PUB\n" +
                "/SATE_FY3A_L2L3/MULSS/SNC\n" +
                "/SATE_FY3A_L2L3\n" +
                "/SATE_FY3A_L2L3\n" +
                "/SATE_FY3A_L2L3\n" +
                "/SATE_FY3A_L2L3/MWHS/PUB\n" +
                "/SATE_FY3A_L2L3/ERBM/FTS\n" +
                "/SATE_FY3A_L2L3/TOU/TOZ\n" +
                "/SATE_FY3A_L2L3/MERSI/PUB\n" +
                "/SATE_FY3B_L2L3/VIRR/PUB\n" +
                "/SATE_FY3C_L1/PUB/PUB\n" +
                "/SATE_FY3C_L1/PUB/PUB\n" +
                "/SATE_FY3C_L1/PUB/PUB\n" +
                "/SATE_FY3C_L1/PUB/PUB\n" +
                "/SATE_FY3C_L1/PUB/PUB\n" +
                "/SATE_FY3C_L1/PUB/PUB\n" +
                "/SATE_FY3C_L1/PUB/PUB\n" +
                "/SATE_FY3C_L1/PUB/PUB\n" +
                "/SATE_FY3C_L1/PUB/PUB\n" +
                "/SATE_FY3C_L1/PUB/PUB\n" +
                "/SATE_FY3C_L2L3/MWHS/IWP\n" +
                "/SATE_FY3C_L2L3/VIRR\n" +
                "/SATE_FY3C_L2L3/IRAS/OLR\n" +
                "/SATE_FY3C_L2L3/VASS/PUB\n" +
                "/SATE_FY3C_L2L3/GNOS\n" +
                "/SATE_FY3C_L2L3/MWRI\n" +
                "/SATE_FY3C_L2L3/MERSI\n" +
                "/SATE_FY3C_L2L3/SBUS/OZP\n" +
                "/SATE_FY3C_L2L3/SEM\n" +
                "/SATE_FY3C_L2L3/ERBM/FTS\n" +
                "/SATE_FY3C_L2L3/VIRR/NVI\n" +
                "/SATE_FY3C_L2L3/MERSI/NVI\n" +
                "/SATE_FY2E_L2L3/OLR/PUB\n" +
                "/SATE_FY2E_L2L3/TBB/PUB\n" +
                "/SATE_FY2E_L2L3/CTA/PUB\n" +
                "/SATE_FY2E_L2L3/SSI/PUB\n" +
                "/SATE_FY2E_L2L3/UTH/PUB\n" +
                "/SATE_FY2E_L2L3/HPF/PUB\n" +
                "/SATE_FY2E_L2L3/TPW/PUB\n" +
                "/SATE_FY2E_L2L3/SNW/PUB\n" +
                "/SATE_FY2E_L2L3/CLC/PUB\n" +
                "/SATE_FY2G_NOM\n" +
                "/SATE_FY2G_L2L3/pub/pub\n" +
                "/SATE_FY2G_L2L3/pub/pub\n" +
                "/SATE_MULTI_001/H08/PUB\n" +
                "/SATE_FY2E_TROPIC/PUB/PUB\n" +
                "/SATE_FY2G_TROPIC/PUB/PUB\n" +
                "/SATE_FY2F_L2L3/CTA/PUB\n" +
                "/SATE_FY2F_L2L3/CFR/PUB\n" +
                "/SATE_MULTI_003/MET7/MTP_MET7\n" +
                "/SATE_MULTI_003/MET7/SLS_MET7\n" +
                "/SATE_MULTI_003/MET/MSG_MSG\n" +
                "/SATE_MULTI_003/MET/MSG_MPEF\n" +
                "/SATE_MULTI_003/GOES13/MSG3_GOES13\n" +
                "/SATE_MULTI_003/GOES15/MSG3_GOES15\n" +
                "/SATE_MULTI_001/MTSAT/PUB\n" +
                "/SATE_MULTI_001/WEST/PUB\n" +
                "/SATE_POES_001/OTHE/PUB\n" +
                "/SATE_MULTI_003/NA19/L1\n" +
                "/SATE_MULTI_003/NA19/L2\n" +
                "/SATE_MULTI_001/NA16/L2L3\n" +
                "/SATE_MULTI_001/NA18/L1\n" +
                "/SATE_MULTI_001/NA16/L1\n" +
                "/SATE_MULTI_001/NA17/L1\n" +
                "/SATE_MULTI_001/NA18/L1\n" +
                "/SATE_MULTI_001/NA17/L2L3\n" +
                "/SATE_MLT_PROD/MLT/PUB\n" +
                "/SATE_MULTI_003/METOPA/L1\n" +
                "/SATE_MULTI_003/METOPB/L1\n" +
                "/SATE_MULTI_003/METOPA/L1\n" +
                "/SATE_MULTI_003/METOPB/L1\n" +
                "/EUM_2/METOPA\n" +
                "/SATE_MULTI_003/METOPA/L2\n" +
                "/SATE_MULTI_003/METOPB/L2\n" +
                "/SATE_POES_001/OTHE/PUB\n" +
                "/SATE_POES_001/AQUA/PUB\n" +
                "/SATE_MULTI_003/JASON2/PUB\n" +
                "/SATE_FY2G_L2L3/pub/pub\n" +
                "/SATE_FY2G_L2L3/pub/pub\n" +
                "/SATE_FY2G_L2L3/pub/pub\n" +
                "/SATE_FY2G_L2L3/pub/pub\n" +
                "/SATE_FY2G_L2L3/pub/pub\n" +
                "/SATE_FY2G_L2L3/pub/pub\n" +
                "/SATE_FY2G_L2L3/pub/pub\n" +
                "/SATE_FY2G_L2L3/pub/pub\n" +
                "/SATE_FY2G_L2L3/pub/pub\n" +
                "/SATE_FY2G_L2L3/pub/pub\n" +
                "/SATE_FY2G_L2L3/pub/pub\n" +
                "/SATE_FY2G_L2L3/pub/pub\n" +
                "/SATE_FY2G_L2L3/pub/pub\n" +
                "/SATE_FY2G_L2L3/pub/pub\n" +
                "/SATE_FY2G_L2L3/pub/pub\n" +
                "/SATE_FY2G_L2L3/pub/pub\n" +
                "/SATE_FY2E_SVS\n" +
                "/SATE_FY2G_SVS\n" +
                "/SATE_FY3C_L2L3/MWHS/AHP\n" +
                "/SATE_MULTI_003/MET8/MSG1_MSG1\n" +
                "/SATE_MULTI_003/MET8/MSG1_MPEF\n" +
                "/SATE_FY4A_L1/REG/1KM\n" +
                "/SATE_FY4A_L2/REG/ACI\n" +
                "/SEVP_FAX_001/BABJ/PUB\n" +
                "/SEVP_FAX_001/BABJ/PUB\n" +
                "/SEVP_FAX_001/BABJ/PUB\n" +
                "/PUB\n" +
                "/SEVP_WE_001/PROG/PUB\n" +
                "/SEVP_FAX_001/EDZW/PUB\n" +
                "/SEVP_FAX_001/BABJ/PUB\n" +
                "/SEVP_FAX_001/BABJ/PUB\n" +
                "/SEVP_WE_001/PROG/PUB\n" +
                "/SEVP_WE_001/PROG/PUB\n" +
                "/SEVP_WE_001/PROG/PUB\n" +
                "/SEVP_WE_001/PROG/PUB\n" +
                "/SEVP_WE_001/PROG/PUB\n" +
                "/SEVP_WE_001/PROG/PUB\n" +
                "/SEVP_WE_001/PROG/PUB\n" +
                "/SEVP_WE_001/PROG/PUB\n" +
                "/SEVP_WE_001/PROG/PUB\n" +
                "/SEVP_WE_001/PROG/PUB\n" +
                "/SEVP_WE_001/PROG/PUB\n" +
                "/SEVP_WE_001/PROG/PUB\n" +
                "/SEVP_WE_001/PROG/PUB\n" +
                "/SEVP_WE_001/PROG/PUB\n" +
                "/SEVP_WE_001/PROG/PUB\n" +
                "/SEVP_WE_001/PROG/PUB\n" +
                "/SEVP_WE_001/PROG/PUB\n" +
                "/SEVP_WE_001/PROG/PUB\n" +
                "/SEVP_WE_001/PROG/PUB\n" +
                "/SEVP_WE_001/PROG/PUB\n" +
                "/SEVP_WE_001/PROG/PUB\n" +
                "/SEVP_WE_001/PROG/PUB\n" +
                "/SEVP_WE_001/PROG/PUB\n" +
                "/SEVP_WE_001/PROG/PUB\n" +
                "/SEVP_WE_001/PROG/PUB\n" +
                "/SEVP_WE_001/PROG/PUB\n" +
                "/SEVP_WE_001/PROG/PUB\n" +
                "/SEVP_WE_001/PROG/PUB\n" +
                "/SEVP_WE_001/PROG/PUB\n" +
                "/SEVP_WE_001/PROG/PUB\n" +
                "/SEVP_WE_001/PROG/PUB\n" +
                "/SEVP_WE_001/PROG/PUB\n" +
                "/SEVP_WE_001/PROG/PUB\n" +
                "/SEVP_WE_001/PROG/PUB\n" +
                "/SEVP_WE_001/PROG/PUB\n" +
                "/SEVP_WE_001/PROG/PUB\n" +
                "/SEVP_WE_001/PROG/PUB\n" +
                "/SEVP_WE_001/PROG/PUB\n" +
                "/SEVP_WE_001/PROG/PUB\n" +
                "/NWP_MCTR_001/CLDAS/PUB\n" +
                "/NWP_MCTR_001/CLDAS/PUB\n" +
                "/SEVP_WE_001/RFFC/PUB\n" +
                "/SEVP_WE_001/RFFC/PUB\n" +
                "/SEVP_OC_001/OCEN/PUB\n" +
                "/SEVP_CL_001/CLFC/PUB\n" +
                "/SEVP_CL_001/CLFC/PUB\n" +
                "/SEVP_CL_001/CLFC/PUB\n" +
                "/SEVP_CL_001/CLFC/PUB\n" +
                "/SEVP_CL_001/CLFC/PUB\n" +
                "/SEVP_AG_001/AGRM/PUB\n" +
                "/SEVP_EN_001/MCUR/PUB\n" +
                "/SEVP_WE_001/PROG/PUB\n" +
                "/SEVP_WE_001/PROG/PUB\n" +
                "/EMERG_001/PUB/SEVP\n" +
                "/SEVP_EN_001/MCUR/PUB\n" +
                "/SEVP_EN_001/MCUR/PUB\n" +
                "/SEVP_EN_001/MCUR/PUB\n" +
                "/SEVP_EN_001/MCUR/PUB\n" +
                "/SEVP_FKZX/PUB/SATE\n" +
                "/SEVP_FKZX/PUB/SATE\n" +
                "/SEVP_FAX_001/BABJ/PUB\n" +
                "/SEVP_WE_001/PROG/PUB\n" +
                "/NWP_NMC_GEPS/PUB/PUB\n" +
                "/NWP_NMC_TYPH/PUB/PUB\n" +
                "/NWP_NMC_TYPH/PUB/PUB\n" +
                "/SEVP_FAX_001/EDZW/PUB\n" +
                "/SEVP_FAX_001/RJTD/PUB\n" +
                "/NWP_NMC_GEPS/PUB/PUB\n" +
                "/NWP_NMC_GEPS/PUB/PUB\n" +
                "/NWP_NMC_REPS/PUB/PUB\n" +
                "/NWP_NMC_REPS/PUB/PUB\n" +
                "/NWP_NMC_REPS/PUB/PUB\n" +
                "/NWP_NMC_REPS/PUB/PUB\n" +
                "/NWP_NMC_REPS/PUB/PUB\n" +
                "/NWP_NMC_REPS/PUB/PUB\n" +
                "/NWP_NMC_REPS/PUB/PUB\n" +
                "/NWP_NMC_REPS/PUB/PUB\n" +
                "/NWP_NMC_REPS/PUB/PUB\n" +
                "/NWP_NMC_REPS/PUB/PUB\n" +
                "/NWP_NMC_REPS/PUB/PUB\n" +
                "/NWP_NMC_REPS/PUB/PUB\n" +
                "/NWP_NMC_REPS/PUB/PUB\n" +
                "/SEVP_WE_001/PROG/PUB\n" +
                "/SVC_FKZX/PUB/SEVP\n" +
                "/SEVP_WE_001/PROG/PUB\n" +
                "/SVC_FKZX/PUB/SEVP\n" +
                "/SEVP_OC_001/CODAS/PUB\n" +
                "/OTHE_001/CXNW/PUB\n" +
                "/OBS_DOM_STAT/SURF/PUB\n" +
                "/OBS_DOM_STAT/SURF/PUB";
        String[] split = str.split("\n");
        for (String string : split) {
            int i = string.indexOf("/", 2);
            if (i == -1) {
                System.out.println(string);
            }else{
                String substring = string.substring(i);
                System.out.println(substring);
            }
        }

    }

}
