#服务器端口
server:
  port: 8080
spring:
  #数据库配置信息
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot?characterEncoding=utf-8&useSSL=false
    username: root
    password: Admin321***
  #控制台打印sql配置信息
logging:
  level:
    com.mj.springboot.mapper: debug   #对应的mapper包

