#服务器端口
server:
  port: 8081
  servlet:
    context-path: /springboot
  # mysql数据库配置信息
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.107.49.58:3306/springboot?characterEncoding=utf-8&useSSL=false
    username: root
    password: Admin321***
  redis:
    database: 0
    host: 39.107.49.58
    port: 6379
    password: 123456




  #控制台打印sql配置信息
logging:
  level:
    com.mj.springboot.mapper: debug   #对应的mapper包

